INSERT OR IGNORE
INTO authors
(name, tags)
VALUES
('I. Bloch', 'cold atoms, lattices'),
('Immanuel Bloch', 'cold atoms, lattices'),
('Dalibard', 'cold atoms'),
('Salomon', 'cold atoms'),
('Langen', 'cold atoms, molecules'),
('Greiner', 'cold atoms, lattices'),
('Hadzibabic', 'cold atoms'),
('Ferlaino', 'cold atoms'),
('Zwierlein', 'cold atoms'),
('Spielman', 'cold atoms'),
('Laurat', 'cold atoms, quantum optics'),
('Ourjoumtsev', 'cold atoms, quantum optics, Rydberg'),
('Browaeys', 'cold atoms, quantum computing, Rydberg'),
('Lukin', 'cold atoms, quantum computing, Rydberg'),
('Endres', 'cold atoms, quantum computing, Rydberg'),
('Lahaye', 'cold atoms, quantum computing, Rydberg'),
('Schreck', 'cold atoms, quantum computing, Rydberg'),
('Kaufman', 'cold atoms, quantum computing, Rydberg'),
('Regal', 'cold atoms, quantum computing, Rydberg'),
('Pfau', 'cold atoms, quantum computing, Rydberg'),
('Cheinet', 'cold atoms, quantum computing, Rydberg'),
('Brune', 'cold atoms, quantum computing, Rydberg'),
('Sayrin', 'cold atoms, quantum computing, Rydberg'),
('Gleyzes', 'cold atoms, quantum computing, Rydberg'),
('C. Gross', 'cold atoms, quantum computing, Rydberg'),
('Christian Gross', 'cold atoms, quantum computing, Rydberg'),
('S. Will', 'cold atoms, quantum computing, Rydberg'),
('Sebastian Will', 'cold atoms, quantum computing, Rydberg'),
('Saffman', 'cold atoms, quantum computing, Rydberg'),
('Bernien', 'cold atoms, quantum computing, Rydberg'),
('Oberthaler', 'cold atoms'),
('Esslinger', 'cold atoms'),
('Tarruel', 'cold atoms'),
('Gerbier', 'cold atoms'),
('Beugnon', 'cold atoms'),
('Takahashi', 'cold atoms, clocks'),
('Takahashi', 'cold atoms, clocks'),
('J. Ye', 'cold atoms, clocks'),
('Jun Ye', 'cold atoms, clocks'),
('Rauschenbeutel', 'cold atoms, quantum optics'),
('Blumenthal', 'quantum technologies, PICs'),
('Englund', 'quantum technologies, PICs'),
('Chiaverini', 'quantum technologies, PICs'),
('Ketterle', 'cold atoms');
